name: Deploy configuration documentation

on:
  push:
    branches:
      - main
      - "ci/*"
    paths:
      - src/shared/**
      - .github/workflows/deploy.yaml

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Install json-schema-for-humans
        run: pip install json-schema-for-humans
      - name: Install Node.js dependencies
        run: npm ci -w src/shared
      - name: Build dependencies
        run: npm run build:jsonschema -w src/shared
      - name: Generate documentation
        run: |
          mkdir public
          generate-schema-doc src/shared/dist/schema.json public/index.html
      - name: Setup pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./public"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
